[settings]
idiomatic_version_file_enable_tools = ["node", "python"]
not_found_auto_install = true
experimental = true

[settings.python]
venv_auto_create = false
uv_venv_auto = true

[tools]
aichat = "latest"
fzf = "latest"
gh = "latest"
jq = "latest"
neovim = "0.11.5"
node = "latest"
ripgrep = "latest"
rust = "latest"
tmux = "latest"
uv = "latest"
yq = "latest"
zoxide = "latest"
